services:
  open-webui:
    # Using the standard build process
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_OPTIONS: --max-old-space-size=16384
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/backend
      - ./src:/app/src
    environment:
      - ENV=dev
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH_STRATEGY=oauth
      - ENABLE_SIGNUP=true
      - OPEN_WEBUI_PORT=8080
      - NODE_OPTIONS=--max-old-space-size=16384
      - AUTH0_DOMAIN=channelai.us.auth0.com
      - AUTH0_CLIENT_ID=cEewmmCzsdXlyMjYPaVL0R0oG5cUch8S
      - AUTH0_CLIENT_SECRET=ENwpH_67wF05aaFnd5oTHFWmSu9c1bbtdYAFy1mGV-n3L-yJT_mQdHCZ4ilPorOJ
      - AUTH0_AUDIENCE=https://admin-api-prod.shroom.gg
      - AUTH0_CALLBACK_URL=http://localhost:8080/api/v1/auths/oauth/auth0/callback
      - USER_PERMISSIONS_WORKSPACE_MODELS_ACCESS=true
      - BYPASS_MODEL_ACCESS_CONTROL=true
    restart: unless-stopped