/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull web'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 1
 * Build: 1.0.0
 * Runtime: browser:typescript-ampli-v2
 *
 * [View Tracking Plan](https://data.amplitude.com/mushroom/Nexus/events/main/latest)
 *
 * [Full Setup Instructions](https://data.amplitude.com/mushroom/Nexus/implementation/web)
 */

import * as amplitude from '@amplitude/analytics-browser';

export type Environment = 'nexus';

export const ApiKey: Record<Environment, string> = {
  nexus: '4eb2325d2ac16bee4a9e031788ac0066'
};

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration: BrowserOptions = {
  plan: {
    version: '1',
    branch: 'main',
    source: 'web',
    versionId: '999cb79c-590e-4ee0-8e39-d5070524c9dd'
  },
  ...{
    ingestionMetadata: {
      sourceName: 'browser-typescript-ampli',
      sourceVersion: '2.0.0'
    }
  }
};

export interface LoadOptionsBase { disabled?: boolean }

export type LoadOptionsWithEnvironment = LoadOptionsBase & { environment: Environment; client?: { configuration?: BrowserOptions; }; };
export type LoadOptionsWithApiKey = LoadOptionsBase & { client: { apiKey: string; configuration?: BrowserOptions; } };
export type LoadOptionsWithClientInstance = LoadOptionsBase & { client: { instance: BrowserClient; } };

export type LoadOptions = LoadOptionsWithEnvironment | LoadOptionsWithApiKey | LoadOptionsWithClientInstance;

export interface IdentifyProperties {
  "Last Login Time"?: string;
  "Signup Time"?: string;
}

export interface ConversationStartedProperties {
  conversationId: string;
  isMultiModel: string;
  /**
   * misspelled, do not use
   *
   * | Rule | Value |
   * |---|---|
   * | Item Type | string |
   */
  modeIdList?: string[];
  /**
   * | Rule | Value |
   * |---|---|
   * | Item Type | string |
   */
  modelIdList: string[];
  primaryModelId: string;
}

export interface MessageSentProperties {
  conversationId: string;
  isMultiModel: string;
  messageId: string;
  /**
   * | Rule | Value |
   * |---|---|
   * | Type | number |
   */
  messageLength: number;
  /**
   * | Rule | Value |
   * |---|---|
   * | Min Items | 1 |
   * | Item Type | string |
   *
   * @minItems 1
   */
  modelIdList: [string, ...string[]];
  primaryModelId: string;
}

export class Identify implements BaseEvent {
  event_type = amplitude.Types.SpecialEventType.IDENTIFY;

  constructor(
    public event_properties?: IdentifyProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class ConversationStarted implements BaseEvent {
  event_type = 'Conversation Started';

  constructor(
    public event_properties: ConversationStartedProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class MessageSent implements BaseEvent {
  event_type = 'Message Sent';

  constructor(
    public event_properties: MessageSentProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class UserLoggedInWithAuth0 implements BaseEvent {
  event_type = 'User Logged In with Auth0';
}

export class UserLoggedOut implements BaseEvent {
  event_type = 'User Logged Out';
}

export class UserRegisteredWithAuth0 implements BaseEvent {
  event_type = 'User Registered with Auth0';
}

export type PromiseResult<T> = { promise: Promise<T | void> };

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
  private disabled: boolean = false;
  private amplitude?: BrowserClient;

  get client(): BrowserClient {
    this.isInitializedAndEnabled();
    return this.amplitude!;
  }

  get isLoaded(): boolean {
    return this.amplitude != null;
  }

  private isInitializedAndEnabled(): boolean {
    if (!this.amplitude) {
      console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
      return false;
    }
    return !this.disabled;
  }

  /**
   * Initialize the Ampli SDK. Call once when your application starts.
   *
   * @param options Configuration options to initialize the Ampli SDK with.
   */
  load(options: LoadOptions): PromiseResult<void> {
    this.disabled = options.disabled ?? false;

    if (this.amplitude) {
      console.warn('WARNING: Ampli is already intialized. Ampli.load() should be called once at application startup.');
      return getVoidPromiseResult();
    }

    let apiKey: string | null = null;
    if (options.client && 'apiKey' in options.client) {
      apiKey = options.client.apiKey;
    } else if ('environment' in options) {
      apiKey = ApiKey[options.environment];
    }

    if (options.client && 'instance' in options.client) {
      this.amplitude = options.client.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      const configuration = (options.client && 'configuration' in options.client) ? options.client.configuration : {};
      return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...configuration });
    } else {
      console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
    }

    return getVoidPromiseResult();
  }

  /**
   * Identify a user and set user properties.
   *
   * @param userId The user's id.
   * @param properties The user properties.
   * @param options Optional event options.
   */
  identify(
    userId: string | undefined,
    properties?: IdentifyProperties,
    options?: EventOptions,
  ): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options,  user_id: userId};
    }

    const amplitudeIdentify = new amplitude.Identify();
    const eventProperties = properties;
    if (eventProperties != null) {
      for (const [key, value] of Object.entries(eventProperties)) {
        amplitudeIdentify.set(key, value);
      }
    }
    return this.amplitude!.identify(
      amplitudeIdentify,
      options,
    );
  }

 /**
  * Flush the event.
  */
  flush() : PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.flush();
  }

  /**
   * Track event
   *
   * @param event The event to track.
   * @param options Optional event options.
   */
  track(event: Event, options?: EventOptions): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.track(event, undefined, options);
  }

  /**
   * Conversation Started
   *
   * [View in Tracking Plan](https://data.amplitude.com/mushroom/Nexus/events/main/latest/Conversation%20Started)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. conversationId)
   * @param options Amplitude event options.
   */
  conversationStarted(
    properties: ConversationStartedProperties,
    options?: EventOptions,
  ) {
    return this.track(new ConversationStarted(properties), options);
  }

  /**
   * Message Sent
   *
   * [View in Tracking Plan](https://data.amplitude.com/mushroom/Nexus/events/main/latest/Message%20Sent)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. conversationId)
   * @param options Amplitude event options.
   */
  messageSent(
    properties: MessageSentProperties,
    options?: EventOptions,
  ) {
    return this.track(new MessageSent(properties), options);
  }

  /**
   * User Logged In with Auth0
   *
   * [View in Tracking Plan](https://data.amplitude.com/mushroom/Nexus/events/main/latest/User%20Logged%20In%20with%20Auth0)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  userLoggedInWithAuth0(
    options?: EventOptions,
  ) {
    return this.track(new UserLoggedInWithAuth0(), options);
  }

  /**
   * User Logged Out
   *
   * [View in Tracking Plan](https://data.amplitude.com/mushroom/Nexus/events/main/latest/User%20Logged%20Out)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  userLoggedOut(
    options?: EventOptions,
  ) {
    return this.track(new UserLoggedOut(), options);
  }

  /**
   * User Registered with Auth0
   *
   * [View in Tracking Plan](https://data.amplitude.com/mushroom/Nexus/events/main/latest/User%20Registered%20with%20Auth0)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  userRegisteredWithAuth0(
    options?: EventOptions,
  ) {
    return this.track(new UserRegisteredWithAuth0(), options);
  }
}

export const ampli = new Ampli();

// BASE TYPES
type BrowserOptions = amplitude.Types.BrowserOptions;

export type BrowserClient = amplitude.Types.BrowserClient;
export type BaseEvent = amplitude.Types.BaseEvent;
export type IdentifyEvent = amplitude.Types.IdentifyEvent;
export type GroupEvent = amplitude.Types.GroupIdentifyEvent;
export type Event = amplitude.Types.Event;
export type EventOptions = amplitude.Types.EventOptions;
export type Result = amplitude.Types.Result;
